# -*- coding: utf-8 -*-
"""Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ggc39siED8u8yVtUrv3U9PN-TKz_EJJb
"""

import requests
import pandas as pd
from scipy import stats
import numpy
import sys
import csv

def predict_price(area1) -> float:
    """
    This method must accept as input an array `area` (represents a list of areas sizes in sq feet) and must return the respective predicted prices (price per sq foot) using the linear regression model that you build.

    You can run this program from the command line using `python3 regression.py`.
    
    """
    area = []
    price=[]
    
    
    with open('linreg_train.csv') as csvfile:
        readCSV = csv.reader(csvfile, delimiter=',')
        dates = []
        price = []
        area=[]
        i=0
        for row in readCSV:
            #print(row)
            if i==0:
                area.append(row[1:])
                i=i+1
            else:
                price.append(row[1:])
            

    #print(date)
    #print(area[0])
    #print(type(price[0][0]))
    #x = np.array()
    x=[]
    for i in area[0]:
        x.append(float(i))
    #print(len(x))
    y=[]
    for i in price[0]:
        y.append(float(i))
    x = numpy.array(x)
    y = numpy.array(y)
    grad, intercept, r_val,p_val,std_err = stats.linregress(x,y)
    print('grad',grad)
    print('intercept',intercept)
    #print(area1)
    pred =[]
    for i in area1:
        yhat = grad*i+intercept
        pred.append(yhat)
    return(numpy.array(pred))
    # YOUR IMPLEMENTATION HERE
    ...

if __name__ == "__main__":
    # DO NOT CHANGE THE FOLLOWING CODE
    from data import validation_data
    areas = numpy.array(list(validation_data.keys()))
    prices = numpy.array(list(validation_data.values()))
    predicted_prices = predict_price(areas)
    rmse = numpy.sqrt(numpy.mean((predicted_prices - prices) ** 2))
    try:
        assert rmse < 170
    except AssertionError:
        print(f"Root mean squared error is too high - {rmse}. Expected it to be under 170")
        sys.exit(1)
    print(f"Success. RMSE = {rmse}")

